language: c
compiler:
  - gcc
sudo: required
services:
  - docker
install: travis_wait date

matrix:
    include:
        - env: "job1"
          script: 
            - pwd; ls -l ; ./compiling
        - env: "job2"
          script: 
            - pwd; ls -l ;./compiling
        - env: "job3"
          script: 
            - sleep 30; pwd; ls -l ; ./compiling
        - env: "job4"
          script: 
            - pwd; set; ./compiling


