language: c
compiler:
  - gcc
sudo: required
services:
  - docker
install: travis_wait date

matrix:
    include:
        - env: "job1"
          script: 
            - echo "1 command"
            - echo "2 command"
        - env: "job2"
          script: 
            - echo "1 command" && echo "2 command"
        - env: "job3"
          script: 
            - echo "1 command" ; echo "2 command"
        - env: "job4"
          script: 
            - set
