#!/bin/bash

set -x
pwd

if [ "${SHIPPABLE}" = "true" -o "${SEMAPHORE}" = "true" -o "${TRAVIS}" = "true" ]
then
	ln -svf Makefile-docker Makefile
else
	ln -svf Makefile-without-docker Makefile
fi

ls -l Makefile

#set

