#!/bin/bash

set -x

echo "configure"
lsb_release -a

wget --version
curl --version
gcc --version
g++ --version
clang --version
sort --version
sed --version

echo "PKG_CONFIG: `pkg-config --version`"

NR_CPUS=`cat /proc/cpuinfo | grep processor | wc -l`
echo "NR_CPUS=${NR_CPUS}"
free
df -h
set
echo "HOME=$HOME"
whoami

