#!/bin/bash

set -x

ID=`docker ps -a --filter "name=kanapi-cli" -q`
docker start ${ID}
docker exec ${ID} /configure
if [ "${TRAVIS}" = "true" ]
then
	docker exec -e TRAVIS="true" -e PKG_COMMAND="t_gui" ${ID} /_start_install 
else
	docker exec -e PKG_COMMAND="t_gui" ${ID} /_start_install 
fi

docker stop ${ID}

